### ISSUE TITLE
Dialogue To-Dos

### ISSUE THREAD

**Issue by 5A11** [fetchai/agents-aea#1261]
### To-Dos:

**Current issues/ugly designs**

- [x] The `create_dialogue` method in Dialogues is ugly, and in general, the 3 layered subclass dependencies (base, instance such as Fipa, derived dialogue) is not the cleanest. Make dialogue creation explicit. [v0.6!]  (Stage 3)
- [x] The current implementation means: the role of an agent in a dialogue is always determined via the first move (whether the move is by the agent or its counterparty) via the `role_from_first_message()` method (NOTES) [v0.5] > create(cfp_msg, role, counterparty) replaces update()
- [x] Two places can update the dialogue reference on receiving second message, `_update_self_initiated_dialogue_label_on_second_message()` in `Dialogues` and `Dialogue`. [v0.5.1]
- [x] After studying how dialogues are used in the skills, I propose adding the following 3 methods that would further simplify their usage. The idea is, one should not worry about `message_id`, `dialogue_reference`, `counterparty` and sometimes `target`, if one is creating messages in the context of a dialogue. Those fields can be automatically set, which should result in reduced accidental errors in setting those fields. (USAGE)
In `Dialogue`:
```
reply(self, message_target, performative, **kwargs) -> Dialogue
```
- [x] Apply usage to all skills:  (Stage 2)
*************************
dialogues.update(incoming_message) —> Optional[Dialogue]
dialogues.create(counterparty, performative, **kwargs) —> Tuple[Message, Dialogue]
dialogue.reply(target_message, performative, **kwargs) —> Message
*************************
- [x] Modify update to not have create & reply. (Stage 1)
- [x] handle incoming (update > handle & log); raise outgoing (reply > raise, create > raise) (Stage 1)
- [x] assert the replied target message exists. (Stage 1)
- [x] apply couterparty/is_incoming deprecation throughout all code (Stage 1)

**Docs**
- [ ] Docs update

**Test**
- [x] Tests for the dialogue

**Refactoring**
- [x] Consolidate `_incoming` and `_outgoing` into one.  (Stage 1)
- [x] `sender` and `receiver` fields in messages is cleaner than `is_incoming`, `counterparty`. Both can be automatically assigned so developer does not have to worry about it.

### Done

- [x] Update base `Message` and `FipaMessage` classes and the generator so `message_id`, `target`, `dialogue_reference`, `performative`, etc are accessible. And create an empty `Performatives` enum in the base `Message` class so instance, e.g. Fipa, `Performatives` extend it.
- [x] AgentRole > Role [v0.5]
- [x] Having to manually set `counterparty` for self-created messages. It is only needed for self created initial messages. This can be removed once a new create_dialogue method is added which gets the counterparty as a field (see below), and so the counterparty can be set for every message sent in that dialogue. [v0.5.0]
**Commencement**
- [x] Have `Commencement: [cfp]` in the specification that describes the list of first messages. This is currently inferred from the reply structure (the move that does not reply to anything else is the initial move). This is problematic because: 
Imagine a simple generic dialogue where the two agents just send `inform(msg)` to each other. Then:
```
speech-acts:
  inform: msg: ct:Message
```
and
```
reply:
inform: {inform}
```
In this case, there are no moves that are not a reply to others, thus `len(initial_performative_list) == 0`.

Also, one could imagine a scenario where there are more than one move (say 2 moves) which are not replies to other moves. In this case, if the dialogue is started with one of these moves, the other one is dangling (i.e. would not be possible to use because it cannot reply to anything else) and vice versa. Thinking generically, there might be use for such designs where you allow two different openings for your dialogues. Then depending on the opening move in a specific dialogue, some of the speech-acts are used, and the rest would be useless in that instance.
- [x] Adding the following 2 methods that would further simplify dialogue usage:
In `Dialogues`:
```
*_dialogues.create(self, counterparty, performative, **kwargs) -> Tuple[Message, Dialogue]
```
In `Dialogue`:
```
reply(self, message, performative, **kwargs) -> Tuple[Message, Dialogue]
```
- [x] Rename `AgentRole` enum to `FipaRoles` and update all usage. This is so it would be `{}Roles` for other dialogues.

**Comment by DavidMinarsch** [comment]
Some observations:
- dialogues are scoped to a skill; there is no shared access between skills
- timeout in dialogues: no concept of this atm
- persistence: we do not currently persists anything, everything purely in memory atm;
- all dialogues are bilateral

ToDos:
- [ ] create one dialogue manager for all dialogue types in a skill; expose on skill context
- [ ] update intro to dialogues

**Comment by DavidMinarsch** [comment]
- [ ] dialogue module needs to be moved to protocols; it's no longer correct to leave it in helpers; also wrong dependency structure

**Comment by DavidMinarsch** [comment]
- [ ] make dialogue properties accessible on protobuf level?

**Comment by DavidMinarsch** [comment]
- [ ] separation between internal and external protocols is not clear; for the dialogue constructor it would help if we knew what type of protocol we are dealing with. For internal protocols we would like to set the component_id as the address, vs for external ones we'd like to set the agent address as the address.
