### ISSUE TITLE
Outstanding bugs/issues with CLI

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#564]
**Is your feature request related to a problem? Please describe.**
remote_registry = Oleg's server
local_registry = 'packages` folder
assumption_for_local:
root_dir:
 > packages
 > my_first_agent(agent dir)
A number of issues remain:
- [x] `aea remove [package] [NAME]` still based on name only > should be both possible to do `aea remove [package] [NAME]` and `aea remove [package] [PUBLIC_ID]` (MARCO) #566 
- [x] missing agents in search command > add `aea search agents` command (MARCO/OLEG) 
#569 
- [x] search command should work from root too > currently, search only works properly from within an agent project dir..it should also work from the root dir (which is assumed to contain `packages`) > search command should take into account any `packages` dir on same level and one level above (MARCO) #567
- [x] error handling of public id on cli not ideal > gracefully handle error cases (MARCO) #571
- [x] error handling if not connected to remote > gracefully handle (OLEG) #593
- [x] `aea add package` command does not add based on public id, it just uses the name > the add command should check that it adds the correct version and author (MARCO) #570
- [x] apply `--registry` flag throughout (OLEG) #593
- [x] `aea fetch [AGENT_PROJECT]` does not install dependencies (OLEG) > see #565, #593

Open issue:
should we rename all packages to public id path?

**Describe the solution you'd like**
See above.

**Comment by DavidMinarsch** [comment]
<img width="624" alt="Screenshot 2019-12-31 at 16 22 58" src="https://user-images.githubusercontent.com/19314578/71627363-f2da7980-2be9-11ea-90c2-d9695809e998.png">
<img width="638" alt="Screenshot 2019-12-31 at 16 23 43" src="https://user-images.githubusercontent.com/19314578/71627410-24ebdb80-2bea-11ea-8877-ff18d96fcd73.png">
Two issues to be addressed by @panasevychol  ^^
