### ISSUE TITLE
Generator To-Dos

### ISSUE THREAD

**Issue by 5A11** [fetchai/agents-aea#976]
## To-Dos:

- [x] Further refactoring and cleaning up
- [ ] Consolidate `ProtocolSpecification` (constructed from loading the config) and `PythonicProtocolSpecification`. Make one ProtocolSpecification that a) validates the spec, b) extracts fields into Pythonic fields (e.g. roles, initiation, etc) as well as auxiliary fields (e.g. all custom_types, all_performatives, etc).
- [ ] Change formatting of the raw generated files from black to normal, now that black is automatically applied. This would simplify the generator's code. Think about simplifying specification of code blocks as files or multi-line strings.
- [x] Make it so the Performative enum in an instance Message class is a subclass of the performative enum in the base Message class.
- [x] Make it so the type hinting takes into account whether some x must be of type A (i.e. `x: A` as in the current implementation) vs when x must be of type "A or any of its subclasses" (i.e. `x: Type(A)`). For instance, many method arguments such as `Performative` in `Dialogues.create()`, `message` in `Dialogues.update()`, etc, must be of the latter kind.

- More Tests:
  - [ ] More tests on correct and incorrect specifications

## Notes:

- There is a constraint on protobuf maps<X, Y> which means the keys cannot be of types bytes, float, double or another message. Currently we implement `dicts` as `maps` and by extension, take this constraint on board. Is this desired, or do we want to switch to XXPairs, or a mix of the two approaches (i.e. the latter where the former isn't allowed)?
- A note on how optional fields in proto3 are represented (discussion here https://github.com/protocolbuffers/protobuf/issues/1606).
- Problem: Float types do not quite match when serialised and then deserialised using protocol buffer. Some inaccuracy in protobuf serialisation/deserialisation process. Example, 5.0 when serialised and then deserialised is 4.999999998.
- Support for custom types is very limited in the generator. This is due to the lack of a mechanism for describing types in a infrastructure-independent language. The type's class implementation and protobuf encoding/decoding still have to be provided in the custom_types.py module and the protobuf schema code is provided in the specification, all pointing to the temporary nature of support for custom types. 

## Done:

- [x] Format checking content types in protocol specifications (e.g. using regexp) & validation yaml files (multi page) [v0.5]
- [x] Add test that verifies `black` and `protoc` exist in cli generate test file.
- [x] Test that the test protocol package matches the output of the latest generator
- [x] encode should be staticmethod not classmethod in custom_types. [v0.3]
- [x] There is a constraint on protobuf `maps<X, Y>`: Keys cannot be `bytes`, `float`, `double`, or another `message` type. Do we take this constraint on board generally in protocol specification or perhaps replace `maps<X, Y>` with `repeated XXPairs`?  [v0.4, repeat for those not supported as keys by maps]
- [x] Encapsulate some of the cli functionality related to the running of the generator (e.g. loading protocol specification, running black on the output), and use it in the test that programmatically uses the generator (e.g. the one comparing test package with latest generator output); first separate into four parts a) spec validation; b) spec > protobuf; c) generate python files; d) apply black on python files;  should be possible to run a&b only [v0.5] 
- [x] change performative name in generated protocols schema file so they are XXX_Performative. This way a performative and content of the same name would be allowed (now, both would be messages with the same name, and protobuf complains). [v0.3]
- [x] (NOTE) In general, at the current point in time, it is best to declare that the generator does not support the generation of custom types. Currently when generating a protocol whose specification contains custom types, the custom type's class implementation and protobuf serialisation code still have to be provided in the custom_types.py module after the generation and the protobuf schema code must be provided in the specification, which is not at all a clean solution. The current generator's support for custom types is merely a hack to allow existing protocols to be generated. [we will maintain the temporary solution for the time beeing; v0.3 add this note to the docs]
- [x] (Note) In `proto3`, which is the version used by the generator, there is no way to check whether an `optional` field has been set or not (see discussion here https://github.com/protocolbuffers/protobuf/issues/1606). In proto3, all `optional` fields are assigned a default value (e.g. 0, false). Therefore, there is no way to know whether an optional field whose value is the default value was not set or was in fact set but its value happens to be the default value. This lead to the creation of a second field per each optional field that declares whether the field is set or not in the proto schema generated by the generator, which is not a clean solution.  [we will maintain the temporary solution for the time beeing; v0.3 add this note to the docs]
- [x] (Note) `float` types do not match when serialised and then deserialised using protocol buffer. It seems to be some inaccuracy in protobuf serialisation/deserialisation process. [v0.3 add this note to the docs]
- [x] Currently if there is a `protoc` error, the error is displayed on the terminal but also the protocol is generated without the `*_pb2.py` file. Change the behaviour so in such a case, nothing is generated and the `protoc` error is relayed as a framework error. [v0.5]
- [x] Change the class variable line generated in the `message.py` module from `ProtocolId(“fetchai”, “ledger_api”, “0.2.0”)` to `ProtocolId.from_str(“fetchai/ledger_api:0.2.0")` in all protocols.
- [x] More Tests
- [x] There is a mismatch between protobuf types and message types. For example, protobuf code says `proposal` is a `list` of `bytes`. In `message.py` it is actually a list of `Descriptions` which is converted to `bytes` in `serialisation.py` via `pickle`. To remove `pickle`, these types must be designed with protobuf.
 - [x] End-to-end tests involving that covers all possible valid and invalid content types [v0.4]
